### ISSUE TITLE
val 问题

### ISSUE THREAD

**Issue by wang7393** [liux0614/yolo_nano#22]
验证模型的时候随机性的报如下错误，有遇到过没
ting Model ----
Traceback (most recent call last):
  File "main.py", line 118, in <module>
    val(model, val_dataloader, epoch, opt, val_logger, visualizer)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/wangxiaobo_work/10-torch/yolo_nano/val.py", line 50, in val
    true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_matrics))]
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by modddypan** [comment]
数据集格式不对吧

**Comment by xerus1007** [comment]
我也遇到一樣的問題，請問大老們有解嘛?

**Comment by Interesting6** [comment]
应该是非极大值抑制里面未考虑无物体的情况
