### ISSUE TITLE
运行时报错中断，NameError: name 'vis' is not defined

### ISSUE THREAD

**Issue by PIPIWAN** [liux0614/yolo_nano#34]
Epoch 4/10
```
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    val(model, val_dataloader, epoch, opt, val_logger, visualizer)
  File "/home/z/anaconda3/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/z/桌面/yolo_nano-master/val.py", line 61, in val
    vis.plot_metrics(metric_table_data, batches_done, env='main')
NameError: name 'vis' is not defined
```

**Comment by PIPIWAN** [comment]
已解决 vis改成全称即可
